name: CI/CD Pipeline with Docker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t aceest_fitness_test .

      - name: Run tests inside Docker container
        run: |
          docker run --rm aceest_fitness_test pytest test.py
